/*
================================================================================
QUERY: Analisis VG con edad alineada al notebook y salida agrupada por poliza
================================================================================
Objetivo:
- Mantener el ajuste de edad: usar CL.EDAD_CLIENTE (sin recalculo por fecha).
- Entregar salida agregada como antes (nivel poliza), no a nivel asegurado-amparo.
================================================================================
*/

WITH V_POLIZA_V AS (
    SELECT DISTINCT
        P.NUMERO_POLIZA,
        P.POLIZA_ID,
        P.SUCURSAL_ID,
        CASE
            WHEN PL.PRODUCTO_ID IN (53456,57948,119,111) THEN 'VIDA_INTEGRAL'
            WHEN PL.PRODUCTO_ID IN (57254,57248)         THEN 'PES'
            ELSE 'OTROS_PRODUCTOS'
        END AS GRUPO_PRODUCTO
    FROM MDB_SEGUROS_COLOMBIA.V_POLIZA P
    INNER JOIN MDB_SEGUROS_COLOMBIA.V_POLCERT_COBERTURA PC
        ON P.POLIZA_ID = PC.POLIZA_ID
    INNER JOIN MDB_SEGUROS_COLOMBIA.V_PLAN_INDIVIDUAL PL
        ON PL.PLAN_INDIVIDUAL_ID = PC.PLAN_INDIVIDUAL_ID
    INNER JOIN MDB_SEGUROS_COLOMBIA.V_PRODUCTO PR
        ON PR.PRODUCTO_ID = PL.PRODUCTO_ID
    INNER JOIN MDB_SEGUROS_COLOMBIA.V_RAMO R
        ON R.RAMO_ID = PR.RAMO_ID
    INNER JOIN MDB_SEGUROS_COLOMBIA.V_SUCURSAL SUC
        ON P.SUCURSAL_ID = SUC.SUCURSAL_ID
    INNER JOIN MDB_SEGUROS_COLOMBIA.V_CANAL_COMERCIAL CAN
        ON CAN.CANAL_COMERCIAL_ID = SUC.CANAL_COMERCIAL_ID
    INNER JOIN MDB_SEGUROS_COLOMBIA.V_GRUPO_CANAL_COMERCIAL GPC
        ON CAN.GRUPO_CANAL_COMERCIAL_ID = GPC.GRUPO_CANAL_COMERCIAL_ID
    WHERE R.RAMO_ID = 274
      AND PL.PRODUCTO_ID IN (53456,57948,119,111,57254,57248)
      AND GPC.GRUPO_CANAL_COMERCIAL_ID IN (24390648,24390649)
),

/* Edad alineada al notebook actual: se toma la edad de la fuente */
MCER AS (
    SELECT
        MCER.POLIZA_CERTIFICADO_ID,
        MCER.POLIZA_ID,
        MCER.MES_ID,
        MCER.ESTADO_CERTIFICADO_CD,
        MCER.ASEGURADO_ID,
        CL.SEXO_CD,
        MAX(CAST(CL.EDAD_CLIENTE AS INTEGER)) AS EDAD_CLIENTE
    FROM MDB_SEGUROS_COLOMBIA.V_HIST_POLIZA_CERT_MSTR MCER
    LEFT JOIN MDB_SEGUROS_COLOMBIA.V_CLIENTE CL
        ON CL.CLIENTE_ID = MCER.ASEGURADO_ID
    INNER JOIN V_POLIZA_V P
        ON P.POLIZA_ID = MCER.POLIZA_ID
    WHERE MCER.MES_ID = 202512
    GROUP BY
        MCER.POLIZA_CERTIFICADO_ID,
        MCER.POLIZA_ID,
        MCER.MES_ID,
        MCER.ESTADO_CERTIFICADO_CD,
        MCER.ASEGURADO_ID,
        CL.SEXO_CD
),

BASE_CERT_AMPARO AS (
    SELECT
        P.GRUPO_PRODUCTO,
        PC.MES_ID,
        PC.POLIZA_ID,
        P.NUMERO_POLIZA,
        PC.POLIZA_CERTIFICADO_ID,
        MCER.ASEGURADO_ID,
        MCER.EDAD_CLIENTE,
        MCER.SEXO_CD,
        CASE
            WHEN PC.AMPARO_ID = 55431 THEN 'Auxilio de repatriacion'
            WHEN PC.AMPARO_ID IN (417, 817, 60081) THEN 'Auxilio funerario'
            WHEN PC.AMPARO_ID IN (55348, 63712) THEN 'Auxilio por maternidad/paternidad'
            WHEN PC.AMPARO_ID IN (59976, 17712, 63711, 63714, 60059) THEN 'Bono canasta'
            WHEN PC.AMPARO_ID IN (55346, 63716) THEN 'Bono para adecuaciones del hogar'
            WHEN PC.AMPARO_ID IN (5950, 55347, 63715) THEN 'Bono para educacion'
            WHEN PC.AMPARO_ID = 56031 THEN 'EG ANTICIPO'
            WHEN PC.AMPARO_ID IN (221, 64984, 63719, 63718) THEN 'EG INDEPENDIENTE'
            WHEN PC.AMPARO_ID IN (726, 63720) THEN 'Gastos de Curacion'
            WHEN PC.AMPARO_ID = 294 THEN 'Invalidez por accidente'
            WHEN PC.AMPARO_ID = 306 THEN 'Invalidez por enfermedad'
            WHEN PC.AMPARO_ID IN (745, 63723, 63721, 63722, 404, 366) THEN 'ITP'
            WHEN PC.AMPARO_ID IN (249, 963, 63689, 63690, 19761, 555) THEN 'Muerte accidental'
            WHEN PC.AMPARO_ID IN (7068, 63694) THEN 'Perdida parcial de la capacidad laboral'
            WHEN PC.AMPARO_ID IN (5048, 5047) THEN 'Renta por hospitalizacion'
            WHEN PC.AMPARO_ID IN (135, 63695) THEN 'Renta por hospitalizacion Basico'
            WHEN PC.AMPARO_ID = 63696 THEN 'Renta por hospitalizacion UCI'
            WHEN PC.AMPARO_ID IN (48425, 63725, 63692) THEN 'Renta por incapacidad'
            WHEN PC.AMPARO_ID = 63697 THEN 'Renta por incapacidad por accidente'
            WHEN PC.AMPARO_ID IN (930, 63717) THEN 'VIDA'
            ELSE TRIM(CAST(PC.AMPARO_ID AS VARCHAR(50)))
        END AS AMPARO_GRUPO,
        MIN(PC.AMPARO_ID) AS AMPARO_ID,
        MAX(CAST(PC.VALOR_ASEGURADO_INICIAL AS DECIMAL(18,2))) AS VALOR_ASEGURADO,
        SUM(CAST(PC.VALOR_PRIMA AS DECIMAL(18,2))) AS VALOR_PRIMA
    FROM MDB_SEGUROS_COLOMBIA.V_HIST_POLCERT_COBERTURA_MSTR PC
    INNER JOIN MCER
        ON  MCER.POLIZA_CERTIFICADO_ID = PC.POLIZA_CERTIFICADO_ID
        AND MCER.MES_ID                = PC.MES_ID
    INNER JOIN V_POLIZA_V P
        ON PC.POLIZA_ID = P.POLIZA_ID
    WHERE PC.MES_TASA_ID = 202512
      AND MCER.ESTADO_CERTIFICADO_CD = 4
      AND MCER.EDAD_CLIENTE NOT IN (-1, 0)
      AND PC.VALOR_ASEGURADO_INICIAL > 3
    GROUP BY
        P.GRUPO_PRODUCTO,
        PC.MES_ID,
        PC.POLIZA_ID,
        P.NUMERO_POLIZA,
        PC.POLIZA_CERTIFICADO_ID,
        MCER.ASEGURADO_ID,
        MCER.EDAD_CLIENTE,
        MCER.SEXO_CD,
        CASE
            WHEN PC.AMPARO_ID = 55431 THEN 'Auxilio de repatriacion'
            WHEN PC.AMPARO_ID IN (417, 817, 60081) THEN 'Auxilio funerario'
            WHEN PC.AMPARO_ID IN (55348, 63712) THEN 'Auxilio por maternidad/paternidad'
            WHEN PC.AMPARO_ID IN (59976, 17712, 63711, 63714, 60059) THEN 'Bono canasta'
            WHEN PC.AMPARO_ID IN (55346, 63716) THEN 'Bono para adecuaciones del hogar'
            WHEN PC.AMPARO_ID IN (5950, 55347, 63715) THEN 'Bono para educacion'
            WHEN PC.AMPARO_ID = 56031 THEN 'EG ANTICIPO'
            WHEN PC.AMPARO_ID IN (221, 64984, 63719, 63718) THEN 'EG INDEPENDIENTE'
            WHEN PC.AMPARO_ID IN (726, 63720) THEN 'Gastos de Curacion'
            WHEN PC.AMPARO_ID = 294 THEN 'Invalidez por accidente'
            WHEN PC.AMPARO_ID = 306 THEN 'Invalidez por enfermedad'
            WHEN PC.AMPARO_ID IN (745, 63723, 63721, 63722, 404, 366) THEN 'ITP'
            WHEN PC.AMPARO_ID IN (249, 963, 63689, 63690, 19761, 555) THEN 'Muerte accidental'
            WHEN PC.AMPARO_ID IN (7068, 63694) THEN 'Perdida parcial de la capacidad laboral'
            WHEN PC.AMPARO_ID IN (5048, 5047) THEN 'Renta por hospitalizacion'
            WHEN PC.AMPARO_ID IN (135, 63695) THEN 'Renta por hospitalizacion Basico'
            WHEN PC.AMPARO_ID = 63696 THEN 'Renta por hospitalizacion UCI'
            WHEN PC.AMPARO_ID IN (48425, 63725, 63692) THEN 'Renta por incapacidad'
            WHEN PC.AMPARO_ID = 63697 THEN 'Renta por incapacidad por accidente'
            WHEN PC.AMPARO_ID IN (930, 63717) THEN 'VIDA'
            ELSE TRIM(CAST(PC.AMPARO_ID AS VARCHAR(50)))
        END
),

BASE_CERT_DEDUP AS (
    SELECT *
    FROM BASE_CERT_AMPARO
),

BASE_DEDUP_AJUSTADO AS (
    SELECT
        GRUPO_PRODUCTO,
        MES_ID,
        POLIZA_ID,
        NUMERO_POLIZA,
        POLIZA_CERTIFICADO_ID,
        ASEGURADO_ID,
        EDAD_CLIENTE,
        SEXO_CD,
        AMPARO_GRUPO,
        AMPARO_ID,
        CASE
            WHEN AMPARO_GRUPO = 'VIDA'
            THEN CAST(VALOR_ASEGURADO * 0.6 AS DECIMAL(18,2))
            ELSE VALOR_ASEGURADO
        END AS VALOR_ASEGURADO,
        VALOR_PRIMA
    FROM BASE_CERT_DEDUP
),

BASE_ASEGURADO_AMPARO AS (
    SELECT
        MIN(GRUPO_PRODUCTO)  AS GRUPO_PRODUCTO,
        MIN(MES_ID)          AS MES_ID,
        MIN(POLIZA_ID)       AS POLIZA_ID,
        MIN(NUMERO_POLIZA)   AS NUMERO_POLIZA,
        ASEGURADO_ID,
        MIN(EDAD_CLIENTE)    AS EDAD_CLIENTE,
        MIN(SEXO_CD)         AS SEXO_CD,
        AMPARO_GRUPO,
        MIN(AMPARO_ID)       AS AMPARO_ID,
        SUM(VALOR_ASEGURADO) AS VALOR_ASEGURADO,
        SUM(VALOR_PRIMA)     AS VALOR_PRIMA
    FROM BASE_DEDUP_AJUSTADO
    GROUP BY
        ASEGURADO_ID,
        NUMERO_POLIZA,
        AMPARO_GRUPO
),

BASE_CON_TASAS AS (
    SELECT
        B.*,
        COALESCE(T.TASA, 0) AS TASA_RIESGO,

        CAST(CAST(B.VALOR_ASEGURADO AS DECIMAL(20,6)) * CAST(COALESCE(T.TASA, 0) AS DECIMAL(10,8)) AS DECIMAL(18,2)) AS SIN_ESPERADA,

        CASE
            WHEN B.AMPARO_GRUPO IN ('VIDA') OR B.AMPARO_ID IN (930, 63717)
            THEN B.VALOR_ASEGURADO
            ELSE 0
        END AS VA_VIDA,

        CASE
            WHEN B.AMPARO_GRUPO = 'EG INDEPENDIENTE'
            THEN B.VALOR_ASEGURADO
            ELSE 0
        END AS VA_EG,

        CASE
            WHEN B.AMPARO_GRUPO IN ('ITP')
            THEN B.VALOR_ASEGURADO
            ELSE 0
        END AS VA_ITP,

        CASE
            WHEN B.AMPARO_GRUPO IN ('VIDA') OR B.AMPARO_ID IN (930, 63717)
            THEN CAST(CAST(B.VALOR_ASEGURADO AS DECIMAL(20,6)) * CAST(COALESCE(T.TASA, 0) AS DECIMAL(10,8)) AS DECIMAL(18,2))
            ELSE 0
        END AS SIN_ESP_VIDA,

        CASE
            WHEN B.AMPARO_GRUPO IN ('VIDA', 'EG INDEPENDIENTE', 'ITP') OR B.AMPARO_ID IN (930, 63717)
            THEN CAST(CAST(B.VALOR_ASEGURADO AS DECIMAL(20,6)) * CAST(COALESCE(T.TASA, 0) AS DECIMAL(10,8)) AS DECIMAL(18,2))
            ELSE 0
        END AS SIN_ESP_VIDA_EG_ITP

    FROM BASE_ASEGURADO_AMPARO B
    LEFT JOIN USER_STAGE.DIEGRALL_TASAS_VG T
        ON  T.CODIGO_AMPARO = B.AMPARO_ID
        AND T.EDAD          = B.EDAD_CLIENTE
),

/* Edad promedio por póliza: cada asegurado contado UNA sola vez */
EDAD_PROMEDIO_POLIZA AS (
    SELECT
        NUMERO_POLIZA,
        CAST(AVG(CAST(EDAD_CLIENTE AS DECIMAL(18,3))) AS DECIMAL(18,3)) AS EDAD_PROMEDIO
    FROM (
        -- Obtener cada asegurado UNA sola vez por póliza, eliminando amparos duplicados
        SELECT DISTINCT
            NUMERO_POLIZA,
            ASEGURADO_ID,
            EDAD_CLIENTE
        FROM BASE_ASEGURADO_AMPARO
    ) AS asegurados_unicos
    GROUP BY
        NUMERO_POLIZA
)

SELECT
    MAX(GP.GRUPO_EMPRESARIAL_DESC) AS GRUPO_EMPRESARIAL_DESC,
    MAX(CL.DNI_CLIENTE) AS DNI_TOMADOR,
    MAX(CL.NOMBRE_COMPLETO) AS NOMBRE_TOMADOR,
    MAX(POL.FECHA_INICIO_PRIMERA_VIGENCIA) AS FECHA_INICIO_PRIMERA_VIGENCIA,

    B.NUMERO_POLIZA,
    B.POLIZA_ID,
    MIN(B.GRUPO_PRODUCTO) AS GRUPO_PRODUCTO,

    MAX(K.NOMBRE_CANAL_COMERCIAL) AS NOMBRE_CANAL_COMERCIAL,
    MAX(I.NOMBRE_GRUPO_CANAL_COMERCIAL) AS NOMBRE_GRUPO_CANAL_COMERCIAL,

    MAX(SUC.CODIGO_OP) AS CODIGO_OFICINA,
    MAX(SUC.NOMBRE_SUCURSAL) AS NOMBRE_SUCURSAL,

    MAX(AG.CODIGO_OP) AS CODIGO_ASESOR,
    MAX(AG.NOMBRE_AGENTE) AS NOMBRE_ASESOR,

    SUM(B.VALOR_ASEGURADO) AS VALOR_ASEGURADO_TOTAL,
    SUM(B.VALOR_PRIMA) AS VALOR_PRIMA_TOTAL,

    SUM(B.VA_VIDA) AS VALOR_ASEGURADO_VIDA,
    SUM(B.VA_EG) AS VALOR_ASEGURADO_EG,
    SUM(B.VA_ITP) AS VALOR_ASEGURADO_ITP,

    COUNT(DISTINCT B.ASEGURADO_ID) AS NUMERO_ASEGURADOS,

    MAX(E.EDAD_PROMEDIO) AS EDAD_PROMEDIO,

    SUM(B.SIN_ESPERADA) AS SIN_ESPERADA_TOTAL,
    SUM(B.SIN_ESP_VIDA) AS SIN_ESPERADA_VIDA,
    SUM(B.SIN_ESP_VIDA_EG_ITP) AS SIN_ESPERADA_VIDA_EG_ITP,

    CAST(SUM(B.VALOR_PRIMA) * 1000 / NULLIF(SUM(B.VA_VIDA), 0) AS DECIMAL(18,2)) AS TASA_ACTUAL,

    CAST(SUM(B.SIN_ESPERADA) * 1000 / NULLIF(SUM(B.VA_VIDA), 0) AS DECIMAL(18,2)) AS TPR_PONDERADA_POR_PERSONA,

    CAST(SUM(B.SIN_ESP_VIDA) * 1000 / NULLIF(SUM(B.VA_VIDA), 0) AS DECIMAL(18,2)) AS TPR_SOLO_VIDA,

    CAST(SUM(B.SIN_ESP_VIDA_EG_ITP) * 1000 / NULLIF(SUM(B.VA_VIDA), 0) AS DECIMAL(18,2)) AS TPR_SOLO_VIDA_EG_ITP

FROM BASE_CON_TASAS B
LEFT JOIN EDAD_PROMEDIO_POLIZA E
    ON E.NUMERO_POLIZA = B.NUMERO_POLIZA

INNER JOIN MDB_SEGUROS_COLOMBIA.V_POLIZA POL
    ON POL.POLIZA_ID = B.POLIZA_ID
INNER JOIN MDB_SEGUROS_COLOMBIA.V_SUCURSAL SUC
    ON SUC.SUCURSAL_ID = POL.SUCURSAL_ID
INNER JOIN MDB_SEGUROS_COLOMBIA.V_CANAL_COMERCIAL K
    ON K.CANAL_COMERCIAL_ID = SUC.CANAL_COMERCIAL_ID
INNER JOIN MDB_SEGUROS_COLOMBIA.V_GRUPO_CANAL_COMERCIAL I
    ON I.GRUPO_CANAL_COMERCIAL_ID = K.GRUPO_CANAL_COMERCIAL_ID
INNER JOIN MDB_SEGUROS_COLOMBIA.V_AGENTE AG
    ON AG.AGENTE_ID = POL.AGENTE_LIDER_ID
INNER JOIN MDB_SEGUROS_COLOMBIA.V_CLIENTE CL
    ON CL.CLIENTE_ID = POL.TOMADOR_ID
LEFT JOIN MDB_SEGUROS_COLOMBIA.V_CLIENTE_GRUPO_EMPRESARIAL EMP
    ON EMP.CLIENTE_ID = CL.CLIENTE_ID
LEFT JOIN MDB_SEGUROS_COLOMBIA.V_GRUPO_EMPRESARIAL_SEGM GP
    ON GP.GRUPO_EMPRESARIAL_CD = EMP.GRUPO_EMPRESARIAL_CD

GROUP BY
    B.NUMERO_POLIZA,
    B.POLIZA_ID
;
