/* ============================================================
   SINIESTROS AGREGADOS POR POLIZA (BRUTOS)

   Este query suma el INCURRIDO de la rama BRUTOS del query fuente
    suministrado, al nivel de NUMERO_POLIZA, desde enero de 2022.

   No añade filtros de póliza distintos a los del query fuente.
   ============================================================ */

WITH PARAMETROS AS (
    SELECT
        LAST_DAY(
            CAST(
                CAST(MAX(MCER_SRC.MES_ID) AS VARCHAR(6)) || '01'
                AS DATE FORMAT 'YYYYMMDD'
            )
        ) AS FECHA_CORTE
    FROM MDB_SEGUROS_COLOMBIA.V_HIST_POLIZA_CERT_MSTR MCER_SRC
    WHERE MCER_SRC.MES_ID <= (
        EXTRACT(YEAR FROM ADD_MONTHS(CURRENT_DATE, -1)) * 100
        + EXTRACT(MONTH FROM ADD_MONTHS(CURRENT_DATE, -1))
    )
)

SELECT
    POL.NUMERO_POLIZA,
    SUM(
        CASE
            WHEN ESC.TIPO_OPER_SINIESTRO_CD IN (128, 129, 130)
            THEN ESC.VALOR_SINIESTRO * ESC.VALOR_TASA
            ELSE 0
        END
    ) AS VALOR_INCURRIDO

FROM MDB_SEGUROS_COLOMBIA.V_EVENTO_SINIESTRO_COBERTURA AS ESC

LEFT JOIN MDB_SEGUROS_COLOMBIA.V_SINIESTRO AS SINI
    ON SINI.SINIESTRO_ID = ESC.SINIESTRO_ID

LEFT JOIN MDB_SEGUROS_COLOMBIA.V_RAMO AS RAMO
    ON RAMO.RAMO_ID = ESC.RAMO_ID

LEFT JOIN MDB_SEGUROS_COLOMBIA.V_PLAN_INDIVIDUAL AS PLAN
    ON ESC.PLAN_INDIVIDUAL_ID = PLAN.PLAN_INDIVIDUAL_ID

LEFT JOIN MDB_SEGUROS_COLOMBIA.V_PRODUCTO AS PRO
    ON PLAN.PRODUCTO_ID = PRO.PRODUCTO_ID

LEFT JOIN MDB_SEGUROS_COLOMBIA.V_AMPARO AS AMPA
    ON ESC.AMPARO_ID = AMPA.AMPARO_ID

LEFT JOIN MDB_SEGUROS_COLOMBIA.V_COMPANIA AS CIA
    ON PRO.COMPANIA_ID = CIA.COMPANIA_ID

LEFT JOIN MDB_SEGUROS_COLOMBIA.V_POLIZA AS POL
    ON ESC.POLIZA_ID = POL.POLIZA_ID

LEFT JOIN MDB_SEGUROS_COLOMBIA.V_CONTRATO_MSTR AS CONT
    ON ESC.CONTRATO_ID = CONT.CONTRATO_ID

LEFT JOIN MDB_SEGUROS_COLOMBIA.V_SUCURSAL AS SUC
    ON CONT.SUCURSAL_ID = SUC.SUCURSAL_ID

LEFT JOIN MDB_SEGUROS_COLOMBIA.V_POLIZA_CERTIFICADO_ETL AS POLCERT
    ON ESC.POLIZA_CERTIFICADO_ID = POLCERT.POLIZA_CERTIFICADO_ID

LEFT JOIN MDB_SEGUROS_COLOMBIA.V_CLIENTE AS CLIENTE
    ON POLCERT.ASEGURADO_ID = CLIENTE.CLIENTE_ID

LEFT JOIN MDB_SEGUROS_COLOMBIA.V_CANAL_COMERCIAL AS CANAL
    ON SUC.CANAL_COMERCIAL_ID = CANAL.CANAL_COMERCIAL_ID

LEFT JOIN MDB_SEGUROS_COLOMBIA.V_GRUPO_CANAL_COMERCIAL AS GCAN
    ON CANAL.GRUPO_CANAL_COMERCIAL_ID = GCAN.GRUPO_CANAL_COMERCIAL_ID

CROSS JOIN PARAMETROS PAR

WHERE RAMO.CODIGO_RAMO_OP IN ('084', '183', '083')
    AND CIA.CODIGO_OP = '02'
        -- El corte se hace por la fecha real de ocurrencia, no por el mes contable
        -- del movimiento: incluye desde 2022-01-01 hasta FECHA_CORTE.
    AND SINI.FECHA_SINIESTRO >= DATE '2022-01-01'
        AND SINI.FECHA_SINIESTRO <= PAR.FECHA_CORTE
  AND CANAL.CANAL_COMERCIAL_ID IN (
      24390656,
      28686321,
      24390667,
      48676970,
      24390669
  )

GROUP BY POL.NUMERO_POLIZA;
