/* ============================================================
   SINIESTROS AGREGADOS POR POLIZA (BRUTOS)
   
   Este query trae el VALOR_INCURRIDO total por NUMERO_POLIZA
   filtrando solo registros BRUTOS con filtros del negocio.
   
   Nota: Ejecuta directamente sin tabla volátil para evitar
   errores de transacción en Teradata después de DDL.
   ============================================================ */

SELECT
    POL.NUMERO_POLIZA,
    SUM(
        CASE
            WHEN ESC.TIPO_OPER_SINIESTRO_CD IN (128, 129, 130)
            THEN ESC.VALOR_SINIESTRO * ESC.VALOR_TASA
            ELSE 0
        END
    ) AS VALOR_INCURRIDO

FROM MDB_SEGUROS_COLOMBIA.V_EVENTO_SINIESTRO_COBERTURA AS ESC

LEFT JOIN MDB_SEGUROS_COLOMBIA.V_SINIESTRO AS SINI
    ON SINI.SINIESTRO_ID = ESC.SINIESTRO_ID

LEFT JOIN MDB_SEGUROS_COLOMBIA.V_RAMO AS RAMO
    ON RAMO.RAMO_ID = ESC.RAMO_ID

LEFT JOIN MDB_SEGUROS_COLOMBIA.V_PLAN_INDIVIDUAL AS PLAN
    ON ESC.PLAN_INDIVIDUAL_ID = PLAN.PLAN_INDIVIDUAL_ID

LEFT JOIN MDB_SEGUROS_COLOMBIA.V_PRODUCTO AS PRO
    ON PLAN.PRODUCTO_ID = PRO.PRODUCTO_ID

LEFT JOIN MDB_SEGUROS_COLOMBIA.V_COMPANIA AS CIA
    ON PRO.COMPANIA_ID = CIA.COMPANIA_ID

LEFT JOIN MDB_SEGUROS_COLOMBIA.V_POLIZA AS POL
    ON ESC.POLIZA_ID = POL.POLIZA_ID

LEFT JOIN MDB_SEGUROS_COLOMBIA.V_CONTRATO_MSTR AS CONT
    ON ESC.CONTRATO_ID = CONT.CONTRATO_ID

LEFT JOIN MDB_SEGUROS_COLOMBIA.V_SUCURSAL AS SUC
    ON CONT.SUCURSAL_ID = SUC.SUCURSAL_ID

LEFT JOIN MDB_SEGUROS_COLOMBIA.V_CANAL_COMERCIAL AS CANAL
    ON SUC.CANAL_COMERCIAL_ID = CANAL.CANAL_COMERCIAL_ID

WHERE RAMO.CODIGO_RAMO_OP IN ('084', '183', '083')
  AND CIA.CODIGO_OP = '02'
  AND ESC.MES_ID BETWEEN 201501 AND 202602
  AND CANAL.CANAL_COMERCIAL_ID IN (
      24390656,
      28686321,
      24390667,
      48676970,
      24390669
  )

GROUP BY POL.NUMERO_POLIZA;
